import 'package:flutter/material.dart';

class SongList extends StatelessWidget {
  SongList();

  final List<String> songs = [
    'All Out Of Love - Air Supply',
    'Baker Street - Gerry Rafferty',
    'Careless Whisper - George Michael',
    'Choir Girl - Cold Chisel',
    'Don\'t Stop Believin\' - Journey',
    'Every Breath You Take - The Police',
    'Eye of the Tiger - Survivor',
    'Faith - George Michael',
    'Footloose - Kenny Loggins',
    'Seven Nation Army - The White Stripes',
    'Valerie - Amy Winehouse',
    'Walking on Sunshine - Katrina and the Waves',
    'What\'s Up - 4 Non Blondes',
    'With or Without You - U2',
    'You Give Love a Bad Name - Bon Jovi',
    'Weather With You - Crowded House',
    'Under the Milky Way - The Church',
    'Throw Your Arms Around Me - Hunters & Collectors',
    'Something - The Beatles',
    'One and Only - Adele',
    'You\'re no Good - Linda Ronstadt',
    'Wonderwall - Oasis',
    'Heart of Glass - Blondie',
    'I Want to Break Free - Queen',
    'I Will Survive - Gloria Gaynor',
    'I\'m Gonna Be (500 Miles) - The Proclaimers',
    'I\'m Like a Bird - Nelly Furtado',
    'I\'m Yours - Jason Mraz',
    'I\'m a Believer - The Monkees',
    'I\'m on Fire - Bruce Springsteen',
    'I\'m the Only One - Melissa Etheridge',
    'I\'m Yours - Jason Mraz',
    'I\'ve Got You Under My Skin - Frank Sinatra',
    'I\'ve Had the Time of My Life - Bill Medley & Jennifer Warnes',
    'Eye of the Tiger - Survivor',
    'Every Breath You Take - The Police',
    'Every Little Thing She Does is Magic - The Police',
    'Every Rose Has Its Thorn - Poison',
    'Every Time You Go Away - Paul Young',
    'Everybody Wants to Rule the World - Tears for Fears',
    'Everything I Do, I Do it for You - Bryan Adams',
    'Crazy in Love - Beyonce',
    'Crazy Little Thing Called Love - Queen',
    'Crazy Love - Van Morrison',
    'Crazy - Gnarls Barkley',
    'Creep - Radiohead',
    'Fragile - Sting',
    'Free Fallin\' - Tom Petty',
    'Africa - Toto',
    'American Pie - Don McLean',
    'Another One Bites the Dust - Queen',
    'Back in Black - AC/DC',
    'Bad Moon Rising - Creedence Clearwater Revival',
    'Beautiful Day - U2',
    'Billie Jean - Michael Jackson',
    'Black Velvet - Alannah Myles',
    'Bohemian Rhapsody - Queen',
    'Born in the U.S.A. - Bruce Springsteen',
    'Born to Run - Bruce Springsteen',
    'Brown Eyed Girl - Van Morrison',
    'California Dreamin\' - The Mamas & The Papas',
    'Can\'t Help Falling in Love - Elvis Presley',
    'Chasing Cars - Snow Patrol',
    'Come Together - The Beatles',
    'Comfortably Numb - Pink Floyd',
    'Dancing in the Dark - Bruce Springsteen',
    'Dancing Queen - ABBA',
    'Dream On - Aerosmith',
    'Dreams - Fleetwood Mac',
    'Drops of Jupiter - Train',
    'Everyday is a Winding Road - Sheryl Crow',
    'Fast Car - Tracy Chapman',
    'Free Bird - Lynyrd Skynyrd',
    'Go Your Own Way - Fleetwood Mac',
    'Good Riddance (Time of Your Life) - Green Day',
    'Hallelujah - Leonard Cohen',
    'Hello - Adele',
    'Hey Jude - The Beatles',
    'Hey There Delilah - Plain White T\'s',
    'Hotel California - Eagles',
    'Hungry Like the Wolf - Duran Duran',
    'Hurt - Johnny Cash',
    'I Heard It Through the Grapevine - Marvin Gaye',
    'Imagine - John Lennon',
    'In the Air Tonight - Phil Collins',
    'Jolene - Dolly Parton',
    'Jump - Van Halen',
    'Karma Police - Radiohead',
    'Kashmir - Led Zeppelin',
    'Knocking on Heaven\'s Door - Bob Dylan',
    'Landslide - Fleetwood Mac',
    'Layla - Derek and the Dominos',
    'Lean On Me - Bill Withers',
    'Let It Be - The Beatles',
    'Like a Rolling Stone - Bob Dylan',
    'Livin\' on a Prayer - Bon Jovi',
    'Losing My Religion - R.E.M.',
    'Love Shack - The B-52\'s',
    'Man in the Mirror - Michael Jackson',
    'Mr. Brightside - The Killers',
    'My Girl - The Temptations',
    'Night Moves - Bob Seger',
    'No Woman, No Cry - Bob Marley',
    'Nothing Else Matters - Metallica',
    'November Rain - Guns N\' Roses',
    'Oh, Pretty Woman - Roy Orbison',
    'Old Time Rock and Roll - Bob Seger',
    'One - U2',
    'Paint It Black - The Rolling Stones',
    'Piano Man - Billy Joel',
    'Proud Mary - Creedence Clearwater Revival',
    'Purple Rain - Prince',
    'Radioactive - Imagine Dragons',
    'Red Red Wine - UB40',
    'Respect - Aretha Franklin',
    'Riders on the Storm - The Doors',
    'Ring of Fire - Johnny Cash',
    'Rocket Man - Elton John',
    'Rolling in the Deep - Adele',
    'Runaway Train - Soul Asylum',
    'Running on Empty - Jackson Browne',
    'Santeria - Sublime',
    'Satisfaction - The Rolling Stones',
    'Save Tonight - Eagle-Eye Cherry',
    'Say You Won\'t Let Go - James Arthur',
    'Scar Tissue - Red Hot Chili Peppers',
    'September - Earth, Wind & Fire',
    'She Will Be Loved - Maroon 5',
    'Shooting Star - Bad Company',
    'Should I Stay or Should I Go - The Clash',
    'Smells Like Teen Spirit - Nirvana',
    'Smooth - Santana ft. Rob Thomas',
    'Somebody to Love - Queen',
    'Something Just Like This - The Chainsmokers & Coldplay',
    'Somewhere Over the Rainbow - Israel Kamakawiwo\'ole',
    'Stairway to Heaven - Led Zeppelin',
    'Stand By Me - Ben E. King',
    'Start Me Up - The Rolling Stones',
    'Stayin\' Alive - Bee Gees',
    'Sweet Caroline - Neil Diamond',
    'Sweet Child O\' Mine - Guns N\' Roses',
    'Sweet Home Alabama - Lynyrd Skynyrd',
    'Take Me Home, Country Roads - John Denver',
    'Take on Me - a-ha',
    'Tears in Heaven - Eric Clapton',
    'The Chain - Fleetwood Mac',
    'The Joker - Steve Miller Band',
    'The Sound of Silence - Simon & Garfunkel',
    'The Weight - The Band',
    'Thinking Out Loud - Ed Sheeran',
    'This Love - Maroon 5',
    'Thunderstruck - AC/DC',
    'Tiny Dancer - Elton John',
    'Torn - Natalie Imbruglia',
    'Under Pressure - Queen & David Bowie',
    'Uptown Funk - Mark Ronson ft. Bruno Mars',
    'Use Somebody - Kings of Leon',
    'Viva La Vida - Coldplay',
    'Wagon Wheel - Old Crow Medicine Show',
    'Waiting on the World to Change - John Mayer',
    'Wake Me Up When September Ends - Green Day',
    'Walking in Memphis - Marc Cohn',
    'Wanted Dead or Alive - Bon Jovi',
    'We Are the Champions - Queen',
    'We Will Rock You - Queen',
    'What a Wonderful World - Louis Armstrong',
    'What\'s Going On - Marvin Gaye',
    'When Doves Cry - Prince',
    'Wicked Game - Chris Isaak',
    'Wild World - Cat Stevens',
    'Wish You Were Here - Pink Floyd',
    'With Arms Wide Open - Creed',
    'Wonderful Tonight - Eric Clapton',
    'Yellow - Coldplay',
    'Yesterday - The Beatles',
    'You Are the Sunshine of My Life - Stevie Wonder',
    'You Can Call Me Al - Paul Simon',
    'You Can\'t Always Get What You Want - The Rolling Stones',
    'You Shook Me All Night Long - AC/DC',
    'Your Song - Elton John',
    'Zombie - The Cranberries',
    'Boys of Summer - Don Henley',
    'California Girls - The Beach Boys',
    'Call Me - Blondie',
    'Can\'t Stop the Feeling - Justin Timberlake',
    'Carry on Wayward Son - Kansas',
    'Centerfold - J. Geils Band',
    'Changes - David Bowie',
    'Cheap Thrills - Sia',
    'Clocks - Coldplay',
    'Closer - The Chainsmokers',
    'Come as You Are - Nirvana',
    'Come Sail Away - Styx',
    'Comfortably Numb - Pink Floyd',
    'Complicated - Avril Lavigne',
    'Cool for the Summer - Demi Lovato',
    'Copperhead Road - Steve Earle',
    'Counting Stars - OneRepublic',
  ];

  @override
  Widget build(BuildContext context) {
    return Expanded(
      child: Container(
        margin: const EdgeInsets.only(right: 6.0, left: 6.0, top: 6.0),
        decoration: BoxDecoration(
          color: Colors.white, // Your desired color
          borderRadius: BorderRadius.circular(9.0),
          border: Border.all(
            color: const Color.fromRGBO(
                203, 203, 203, 1.0), // Your desired border color
            width: 1.0, // Your desired border width
          ), // Your desired corner radius
        ),
        child: Column(children: <Widget>[
          Text(
            'Songs',
            style: Theme.of(context).textTheme.headlineLarge,
          ),

          //========================
          // Search Box

          Padding(
            padding: const EdgeInsets.all(8.0),
            child: SizedBox(
              height: 35.0,
              child: TextField(
                decoration: InputDecoration(
                  labelText: "Search",
                  hintText: "Search",
                  prefixIcon: const Icon(Icons.search),
                  suffixIcon: IconButton(
                    onPressed: () {},
                    icon: const Icon(Icons.clear),
                  ),
                  border: const OutlineInputBorder(
                    borderRadius: BorderRadius.all(Radius.circular(25.0)),
                  ),
                ),
              ),
            ),
          ),

          //========================
          // Song List

          Expanded(
            child: ListView(
              padding: const EdgeInsets.all(8),
              children: songs.map((song) {
                return SizedBox(
                  height: 40,
                  child: Container(
                    alignment: Alignment.centerLeft,
                    child: Text(song),
                  ),
                );
              }).toList(),
            ),
          ),
        ]),
      ),
    );
  }
}
